const appRoutes = {
    loginRoute : '/login',
    testRoute : 'test',
    registerRoute : '/register',
    forgotPasswordRoute : '/forgot-password',
    resetPasswordRoute : '/reset-password',
    chatRoute : 'chat',
    productFormRoute : 'product-form',
    productDetailRoute : 'product-detail',
    productSearchListRoute : 'product-search-list',
    sellerProfileRoute : '/seller-profile',
    verifyEmailRoute:'verifyemail', 
    productListRoute : 'product-list',
    dashboardRoute : 'dashboard',
	authPrfixRoute: '/auth',   // It's important to add slash in front of auth to match routes 
	soldProductRoute: 'sold-product',
	paymentStatusRoute: 'payment-status',
	myOrdersRoute: 'my-orders',
	homeRoute: '',
	profileRoute: 'profile',
    soldProductInvoiceRoute: 'order-invoice',
	checkoutRoute: '/check-out',
    notificationRoute: 'notifications',
    addEditSupportTicket: 'support-ticket-form',
    ticketDetailPageRoute: 'ticket-threads',
    aboutUsRoute: 'about-us',
    featureRoute: 'feature',
    faqRoute: 'faq',
    termsConditionRoute: 'terms-condition',
    privacyPolicyRoute: 'privacy-policy',
    helpCenterRoute: 'help-center',
    contactUsRoute: 'contact-us',
    guranteeRoute: 'gurantee',
    buyingQuestionRoute: 'buying-questions',
    sellingQuestionRoute: 'selling-questions',
    whySellWithUsRoute: 'why-sell-with-us',
    
}
export default appRoutes